name: C Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install GCC
      run: sudo apt-get install gcc
    - name: Compile C Code
      run: gcc -o output main.c
    - name: Run C Program
      run: ./output
