name: C Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install GCC and gdb
      run: sudo apt-get install -y gcc gdb
    - name: Compile C Code with Debugging Symbols
      run: gcc -g -o output main.c
    - name: Run C Program with gdb
      run: |
        gdb -batch -ex "run" -ex "bt" ./output
